### ISSUE TITLE
Windows 上用 MinGW (UCRT64) 构建 dev channel 时链接报重定义

### ISSUE THREAD

**Issue by greyishsong** [XJTU-Graphics/dandelion#17]
### Describe the bug 描述 Bug

执行 Dandelion-dev CI 这个 action 时，在 Win64 MinGW UCRT64 平台上编译，`ld` 报了 `multiple definition`，都是关于 fmt 的，详情见 [Action log](https://github.com/XJTU-Graphics/dandelion/actions/runs/10898048218/job/30240549063) 。

### To Reproduce 复现方法

在指定平台上用 Debug 模式编译。

### Runtime Environment (please complete the following information) 环境（请填写下面的信息）

参考 Actions 配置文件。

### Additional context 额外的情况说明

Dev channel 项目主体的 CMakeLists 中没有去掉 `FMT_HEADER_ONLY` 这个宏定义（三个 CMakeLists 中只有这一个我忘记删了），可能会导致 header only 版本和静态库版本一起被使用，进而导致重定义。

**Comment by geezmolycos** [comment]
在本地电脑和 [CI](https://github.com/XJTU-Graphics/dandelion/actions/runs/10899780334) 上测试，https://github.com/XJTU-Graphics/dandelion-dev/commit/db40cc0556e1f5c7cbe7d919123b8913791cd961 已经解决了该问题
