### ISSUE TITLE
Windows 平台使用 MSVC 编译时触发 C5054 警告

### ISSUE THREAD

**Issue by greyishsong** [XJTU-Graphics/dandelion#21]
### Describe the bug 描述 Bug

Windows 平台上使用 MSVC 编译时，Eigen 触发了 [C5054](https://learn.microsoft.com/zh-cn/cpp/error-messages/compiler-warnings/c5054?view=msvc-170) 警告。

详情参见 https://xjtu.app/t/topic/13534。

### To Reproduce 复现方法

在上述平台上编译。

### Runtime Environment (please complete the following information) 环境（请填写下面的信息）
 - OS: Windows 10 / 11 
 - Compiler: MSVC (Visual Studio 2022)
 - Dandelion Version: 1.1.0

**Comment by xiongyuaay** [comment]
可以使用 static_cast 将枚举类型显式转换为整数类型。如下：
```
// dandelion\deps\Eigen\src\Core\TriangularMatrix.h(212,29)
// OuterStrideAtCompileTime = (Options&RowMajor) ? ColsAtCompileTime : RowsAtCompileTime,
OuterStrideAtCompileTime = (static_cast<int>(Options) & static_cast<int>(RowMajor)) ? ColsAtCompileTime : RowsAtCompileTime,
```
```
// dandelion\deps\Eigen\src\Core\Matrix.h(46,40)
/* TransposeMode = (Mode & Upper ? Lower : 0)
                   | (Mode & Lower ? Upper : 0)
                   | (Mode & (UnitDiag))
                   | (Mode & (ZeroDiag)), */
TransposeMode = ((static_cast<int>(Mode) & static_cast<int>(Upper)) ? Lower :  0)
                | ((static_cast<int>(Mode) & static_cast<int>(Lower)) ? Upper : 0)
                | (static_cast<int>(Mode) & static_cast<int>(UnitDiag))
                | (static_cast<int>(Mode) & static_cast<int>(ZeroDiag)),
```

**Comment by greyishsong** [comment]
> 可以使用 static_cast 将枚举类型显式转换为整数类型。

感谢帮忙查找。不过主要问题其实不是修复这个警告，而是为什么它在 CI 环境下没有出现却在实机环境下出现了。可能要麻烦@geezmolycos 有时间开个分支，检查一下我们的 action 执行环境。

**Comment by geezmolycos** [comment]
我在本机上已经复现成功，查看 CI 日志以后发现 CI 中也存在相同问题，但 Github 未报错

针对 MSVC 的 CMakeLists 规则里面没有让所有 warning 变成 error，因此程序可以正常生成，且进程返回值为0，使 Github 没有报错

需要考虑是否添加 MSVC `/WX` 选项，功能类似 GCC `-Werror`

**Comment by greyishsong** [comment]
缺少 pdb 文件导致 LNK4099 是符合预期的，一个能直接调试的 debug 静态库实际上和直接公开源码差别不大。如果没有其他问题的话，我认为可以开启 `/WX`。
