### ISSUE TITLE
Windows MSVC 2019 编译命令行测试出现错误 C2593

### ISSUE THREAD

**Issue by geezmolycos** [XJTU-Graphics/dandelion#23]
### Describe the bug 描述 Bug

Windows 下使用 MSVC 2019 编译 `test` 子目录项目出现诸如以下的问题：

```
D:\work\xjtu-graphics\dandelion\deps\catch2\catch_amalgamated.cpp(7406,33): error C2593: “operator <<”不明确 [D:\work\xjtu-graphics\dandelion\build\test.vcxproj]
D:\work\xjtu-graphics\dandelion\deps\catch2\catch_amalgamated.cpp(6039,10): message : 可能是“std::ostream &Catch::operator <<(std::ostream &,Catch::StringRef)” [D:\work\xjtu-graphics\dandelion\build\test.vcxproj]
D:\work\xjtu-graphics\dandelion\deps\catch2\catch_amalgamated.hpp(761,30): message : 或    “std::ostream &Catch::operator <<(std::ostream &,Catch::StringRef)”[使用参数相关的查找找到] [D:\work\xjtu-graphics\dandelion\build\test.vcxpr
oj]
D:\work\xjtu-graphics\dandelion\deps\catch2\catch_amalgamated.cpp(7406,33): message : 尝试匹配参数列表“(std::basic_ostream<char,std::char_traits<char>>, Catch::StringRef)”时 [D:\work\xjtu-graphics\dandelion\build\test.vcxproj]
```

### To Reproduce 复现方法
1. 使用 dandelion v1.1.0，不修改任何代码
2. `cmake -G "Visual Studio 16 2019" -S test -B build` 生成编译文件
3. `cmake --build "build" --config debug --parallel 8` 编译
4. 出现以上报错

### Runtime Environment (please complete the following information) 环境
 - OS: Windows 10
 - Compiler: MSVC 2019
 - Dandelion Version: 1.1.0

### Additional context 额外的情况说明
Windows 系统的 clang 不出现此问题。

在 catch2 的 issue 区中发现了类似的问题。其中提到，这是 [VS 2019 的 bug](https://github.com/catchorg/Catch2/issues/2174#issuecomment-890860952)，在 2022 版中应该已经修复。

[这篇帖子](https://xjtu.app/t/topic/13580) 中也有详细情况。

**Comment by greyishsong** [comment]
既然之后我们计划完全迁移到 C++ 20 标准，我的看法是直接放弃对 VS 2019 的支持。
