### ISSUE TITLE
MacOS编译失败ld: library not found for -ldandelion-ray-debug

### ISSUE THREAD

**Issue by wsAndy** [XJTU-Graphics/dandelion#3]
实验的commit：
> 179b70581c955786463f22273b9bae629ab473cd
> ceb24df7eb6606851e1f156bc044eef7294ffb0d
上面两个commit都实验了，其中一个为v1.0.2 tag的。

执行步骤：
mkdir build
cd build
cmake .. 
make -j4

报错信息：

ld: library not found for -ldandelion-ray-debug
clang: error: linker command failed with exit code 1 (use -v to see invocation)

实验环境：
MacOS（13.4）

```
clang -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

在Debug和Release两个模式下，都会出现这个问题。
Debug模式下： library not found for -ldandelion-ray-debug
Release模式下： library not found for -ldandelion-ray

**Comment by greyishsong** [comment]
你需要下载 Release 中的静态库文件并放入 *deps* 目录，请参考开发者文档 [Dandelion: 构建](https://dandelion-docs.readthedocs.io/zh-cn/v1.0.2/d8/df1/build.html#dependencies) 。
