### ISSUE TITLE
Layout工具栏下调节模型Center和Scaling属性无响应

### ISSUE THREAD

**Issue by Loturias** [XJTU-Graphics/dandelion#5]
导入模型后调节center和scaling属性对模型渲染无影响.

经检查object.cpp中Object::model()函数返回了Matrix4f::Identity().

请问这是课程内容之一吗？如果是，我将删除此issue.

**Comment by greyishsong** [comment]
> 请问这是课程内容之一吗？

是的，基础部分中有一个实验就是自己计算 Model 变换矩阵，完成后物体的平移/旋转/缩放就会生效。
